set(CMAKE_C_OUTPUT_EXTENSION .o)
set(CMAKE_ASM_OUTPUT_EXTENSION .o)
<<<<<<< HEAD
=======

# Dependency file patterns for XC8
set(CMAKE_DEPFILE_FLAGS_C_AVR "-MD -MF <DEP_FILE> -MT <DEP_TARGET>")
set(CMAKE_DEPFILE_FLAGS_C_PIC "-MD -MF <DEP_FILE>")
set(CMAKE_DEPFILE_FLAGS_C ${CMAKE_DEPFILE_FLAGS_C_AVR})
set(CMAKE_DEPFILE_FLAGS_ASM_AVR "-MD -MF <DEP_FILE> -MT <DEP_TARGET>")
set(CMAKE_DEPFILE_FLAGS_ASM_PIC "-MD -MF <DEP_FILE>")
set(CMAKE_DEPFILE_FLAGS_ASM ${CMAKE_DEPFILE_FLAGS_ASM_AVR})
>>>>>>> a1370d1d27a3cdb330f7d8876be52095cd09e09c
